name: Deploy to production

on:
  push:
    branches:
     - master

jobs:
  vapor-staging:
    name: Check out, build and deploy using Vapor
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 7.3
          tools: composer:v2
          coverage: none
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-dev
    - name: Require Vapor CLI
      run: composer global require laravel/vapor-cli
    - name: Deploy Environment
      run: vapor deploy STAGING --without-waiting
      env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
